spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ask-service
          uri: lb://ask-service
          predicates:
            - Path=/askService/**
          filters:
            - StripPrefix=0
        - id: home-service
          uri: lb://home-service
          predicates:
            - Path=/homeService/**
          filters:
            - StripPrefix=0
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/userService/**
          filters:
            - StripPrefix=0
        - id: page-service
          uri: lb://page-service
          predicates:
            - Path=/pageService/**
          filters:
            - StripPrefix=0