spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ask-service
          uri: lb://ask-service
          predicates:
            - Path=/ask/**
          filters:
            - StripPrefix=1
        - id: home-service
          uri: lb://home-service
          predicates:
            - Path=/home/**
          filters:
            - StripPrefix=1