server:
  port: 1994
  servlet:
    context-path: /userService
spring:
  datasource:
    url: jdbc:mysql://${zlt.datasource.ip}:3306/whyshare?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${zlt.datasource.username}
    password: ${zlt.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hjq.whyshare.code.generator.modle
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

zlt:
  datasource:
    ip: 127.0.0.1
    username: root
    password: root

