eureka:
  client:
    enabled: false
server:
  port: 1991
spring:
  application:
    name: ask-service
  cloud:
    nacos:
      config:
        prefix: ask-service
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
